FCG:
	g++ -o FCG -std=c++0x main.cpp Menu.hpp Menu.cpp InputValidate.hpp InputValidate.cpp Creature.hpp Creature.cpp Vampire.hpp Vampire.cpp Barbarian.hpp Barbarian.cpp BlueMen.hpp BlueMen.cpp Medusa.hpp Medusa.cpp HarryPotter.hpp HarryPotter.cpp

clean:
	rm FCG
