escapeGame:
	g++ -o escapeGame -std=c++0x Attic.cpp Attic.hpp BallRoom.cpp BallRoom.hpp Car.cpp Car.hpp Game.cpp Game.hpp InputValidate.cpp InputValidate.hpp Laboratory.cpp Laboratory.hpp Menu.cpp Menu.hpp OperatingRoom.cpp OperatingRoom.hpp play_game.cpp ReadingRoom.cpp ReadingRoom.hpp Space.cpp Space.hpp

clean:
	rm escapeGame
